//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoManager.OceanReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://engine.ocean.example.com/")]
    public partial class NoSuchAlgorithmException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://engine.ocean.example.com/")]
    public partial class NoSuchProviderException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://engine.ocean.example.com/")]
    public partial class InvalidKeySpecException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://engine.ocean.example.com/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.34283")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://engine.ocean.example.com/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://engine.ocean.example.com/", ConfigurationName="OceanReference1.OceanInterface")]
    public interface OceanInterface {
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CryptoManager.OceanReference1.getSerialNumbersResponse getSerialNumbers(CryptoManager.OceanReference1.getSerialNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoManager.OceanReference1.getSerialNumbersResponse> getSerialNumbersAsync(CryptoManager.OceanReference1.getSerialNumbersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CryptoManager.OceanReference1.getUserNamesResponse getUserNames(CryptoManager.OceanReference1.getUserNamesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoManager.OceanReference1.getUserNamesResponse> getUserNamesAsync(CryptoManager.OceanReference1.getUserNamesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CryptoManager.OceanReference1.NoSuchAlgorithmException), Action="", Name="NoSuchAlgorithmException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CryptoManager.OceanReference1.NoSuchProviderException), Action="", Name="NoSuchProviderException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CryptoManager.OceanReference1.InvalidKeySpecException), Action="", Name="InvalidKeySpecException")]
        [System.ServiceModel.FaultContractAttribute(typeof(CryptoManager.OceanReference1.IOException), Action="", Name="IOException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CryptoManager.OceanReference1.downloadPublicKeyResponse downloadPublicKey(CryptoManager.OceanReference1.downloadPublicKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoManager.OceanReference1.downloadPublicKeyResponse> downloadPublicKeyAsync(CryptoManager.OceanReference1.downloadPublicKeyRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(CryptoManager.OceanReference1.Exception), Action="", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        CryptoManager.OceanReference1.publishPublicKeyResponse publishPublicKey(CryptoManager.OceanReference1.publishPublicKeyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CryptoManager.OceanReference1.publishPublicKeyResponse> publishPublicKeyAsync(CryptoManager.OceanReference1.publishPublicKeyRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSerialNumbers", WrapperNamespace="http://engine.ocean.example.com/", IsWrapped=true)]
    public partial class getSerialNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getSerialNumbersRequest() {
        }
        
        public getSerialNumbersRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSerialNumbersResponse", WrapperNamespace="http://engine.ocean.example.com/", IsWrapped=true)]
    public partial class getSerialNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getSerialNumbersResponse() {
        }
        
        public getSerialNumbersResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserNames", WrapperNamespace="http://engine.ocean.example.com/", IsWrapped=true)]
    public partial class getUserNamesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public getUserNamesRequest() {
        }
        
        public getUserNamesRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getUserNamesResponse", WrapperNamespace="http://engine.ocean.example.com/", IsWrapped=true)]
    public partial class getUserNamesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string[] @return;
        
        public getUserNamesResponse() {
        }
        
        public getUserNamesResponse(string[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadPublicKey", WrapperNamespace="http://engine.ocean.example.com/", IsWrapped=true)]
    public partial class downloadPublicKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public downloadPublicKeyRequest() {
        }
        
        public downloadPublicKeyRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadPublicKeyResponse", WrapperNamespace="http://engine.ocean.example.com/", IsWrapped=true)]
    public partial class downloadPublicKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public downloadPublicKeyResponse() {
        }
        
        public downloadPublicKeyResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="publishPublicKey", WrapperNamespace="http://engine.ocean.example.com/", IsWrapped=true)]
    public partial class publishPublicKeyRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        public publishPublicKeyRequest() {
        }
        
        public publishPublicKeyRequest(string arg0, string arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="publishPublicKeyResponse", WrapperNamespace="http://engine.ocean.example.com/", IsWrapped=true)]
    public partial class publishPublicKeyResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://engine.ocean.example.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public publishPublicKeyResponse() {
        }
        
        public publishPublicKeyResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OceanInterfaceChannel : CryptoManager.OceanReference1.OceanInterface, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OceanInterfaceClient : System.ServiceModel.ClientBase<CryptoManager.OceanReference1.OceanInterface>, CryptoManager.OceanReference1.OceanInterface {
        
        public OceanInterfaceClient() {
        }
        
        public OceanInterfaceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OceanInterfaceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OceanInterfaceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OceanInterfaceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoManager.OceanReference1.getSerialNumbersResponse CryptoManager.OceanReference1.OceanInterface.getSerialNumbers(CryptoManager.OceanReference1.getSerialNumbersRequest request) {
            return base.Channel.getSerialNumbers(request);
        }
        
        public string[] getSerialNumbers(string arg0) {
            CryptoManager.OceanReference1.getSerialNumbersRequest inValue = new CryptoManager.OceanReference1.getSerialNumbersRequest();
            inValue.arg0 = arg0;
            CryptoManager.OceanReference1.getSerialNumbersResponse retVal = ((CryptoManager.OceanReference1.OceanInterface)(this)).getSerialNumbers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoManager.OceanReference1.getSerialNumbersResponse> CryptoManager.OceanReference1.OceanInterface.getSerialNumbersAsync(CryptoManager.OceanReference1.getSerialNumbersRequest request) {
            return base.Channel.getSerialNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoManager.OceanReference1.getSerialNumbersResponse> getSerialNumbersAsync(string arg0) {
            CryptoManager.OceanReference1.getSerialNumbersRequest inValue = new CryptoManager.OceanReference1.getSerialNumbersRequest();
            inValue.arg0 = arg0;
            return ((CryptoManager.OceanReference1.OceanInterface)(this)).getSerialNumbersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoManager.OceanReference1.getUserNamesResponse CryptoManager.OceanReference1.OceanInterface.getUserNames(CryptoManager.OceanReference1.getUserNamesRequest request) {
            return base.Channel.getUserNames(request);
        }
        
        public string[] getUserNames(string arg0) {
            CryptoManager.OceanReference1.getUserNamesRequest inValue = new CryptoManager.OceanReference1.getUserNamesRequest();
            inValue.arg0 = arg0;
            CryptoManager.OceanReference1.getUserNamesResponse retVal = ((CryptoManager.OceanReference1.OceanInterface)(this)).getUserNames(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoManager.OceanReference1.getUserNamesResponse> CryptoManager.OceanReference1.OceanInterface.getUserNamesAsync(CryptoManager.OceanReference1.getUserNamesRequest request) {
            return base.Channel.getUserNamesAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoManager.OceanReference1.getUserNamesResponse> getUserNamesAsync(string arg0) {
            CryptoManager.OceanReference1.getUserNamesRequest inValue = new CryptoManager.OceanReference1.getUserNamesRequest();
            inValue.arg0 = arg0;
            return ((CryptoManager.OceanReference1.OceanInterface)(this)).getUserNamesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoManager.OceanReference1.downloadPublicKeyResponse CryptoManager.OceanReference1.OceanInterface.downloadPublicKey(CryptoManager.OceanReference1.downloadPublicKeyRequest request) {
            return base.Channel.downloadPublicKey(request);
        }
        
        public string downloadPublicKey(string arg0, string arg1) {
            CryptoManager.OceanReference1.downloadPublicKeyRequest inValue = new CryptoManager.OceanReference1.downloadPublicKeyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CryptoManager.OceanReference1.downloadPublicKeyResponse retVal = ((CryptoManager.OceanReference1.OceanInterface)(this)).downloadPublicKey(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoManager.OceanReference1.downloadPublicKeyResponse> CryptoManager.OceanReference1.OceanInterface.downloadPublicKeyAsync(CryptoManager.OceanReference1.downloadPublicKeyRequest request) {
            return base.Channel.downloadPublicKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoManager.OceanReference1.downloadPublicKeyResponse> downloadPublicKeyAsync(string arg0, string arg1) {
            CryptoManager.OceanReference1.downloadPublicKeyRequest inValue = new CryptoManager.OceanReference1.downloadPublicKeyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CryptoManager.OceanReference1.OceanInterface)(this)).downloadPublicKeyAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CryptoManager.OceanReference1.publishPublicKeyResponse CryptoManager.OceanReference1.OceanInterface.publishPublicKey(CryptoManager.OceanReference1.publishPublicKeyRequest request) {
            return base.Channel.publishPublicKey(request);
        }
        
        public string publishPublicKey(string arg0, string arg1) {
            CryptoManager.OceanReference1.publishPublicKeyRequest inValue = new CryptoManager.OceanReference1.publishPublicKeyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            CryptoManager.OceanReference1.publishPublicKeyResponse retVal = ((CryptoManager.OceanReference1.OceanInterface)(this)).publishPublicKey(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CryptoManager.OceanReference1.publishPublicKeyResponse> CryptoManager.OceanReference1.OceanInterface.publishPublicKeyAsync(CryptoManager.OceanReference1.publishPublicKeyRequest request) {
            return base.Channel.publishPublicKeyAsync(request);
        }
        
        public System.Threading.Tasks.Task<CryptoManager.OceanReference1.publishPublicKeyResponse> publishPublicKeyAsync(string arg0, string arg1) {
            CryptoManager.OceanReference1.publishPublicKeyRequest inValue = new CryptoManager.OceanReference1.publishPublicKeyRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((CryptoManager.OceanReference1.OceanInterface)(this)).publishPublicKeyAsync(inValue);
        }
    }
}
